# Generated by Django 6.0.3 on 2026-03-25 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('priceNote', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('sqft', models.CharField(max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('gallery', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='listings.agent')),
            ],
        ),
    ]
