# Generated by Django 6.0.3 on 2026-03-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
