# Generated by Django 6.0.3 on 2026-03-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_property_gallery_alter_agent_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
