# Generated by Django 6.0.3 on 2026-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_property_agent_delete_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewing_time',
            field=models.CharField(blank=True, help_text='e.g., Every Sunday 10 AM - 4 PM', max_length=255, null=True),
        ),
    ]
