# Generated by Django 6.0.3 on 2026-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_property_viewing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished'), ('Part-Furnished', 'Part-Furnished')], default='Unfurnished', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='moving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.CharField(blank=True, help_text='Monthly rent if applicable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
    ]
