# Generated by Django 6.0.3 on 2026-03-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_property_furnished_status_property_moving_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='priceNote',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='viewing_time',
        ),
        migrations.AlterField(
            model_name='property',
            name='rent',
            field=models.CharField(blank=True, help_text='Monthly rent (e.g., £2,500)', max_length=100, null=True),
        ),
    ]
