# Generated by Django 6.0.3 on 2026-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Full Property', 'Full Property'), ('Room', 'Room')], default='Full Property', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric rent for filtering', max_digits=12, null=True),
        ),
    ]
