# Generated by Django 6.0.3 on 2026-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_property_property_type_property_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewing_time',
            field=models.CharField(blank=True, help_text='Available viewing times (e.g., After 6 PM)', max_length=255, null=True),
        ),
    ]
